
name: inglebard/dolibarr_ready:13

on:
  push:
    branches: [ 13 ]
  pull_request:
    branches: [ 13 ]
  schedule:
    - cron:  '15 20 20 * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 13
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: docker build inglebard/dolibarr_ready:13
      run: |
        docker build . -t inglebard/dolibarr_ready:13
    - name: docker push
      run: |
        docker push inglebard/dolibarr_ready:13
