name: inglebard/dolibarr_ready

on:
  push:
    branches: [ 9 ]
  pull_request:
    branches: [ 9 ]
  schedule:
    - cron:  '0 20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 9
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build inglebard/dolibarr_ready:9
      run: |
        docker build . -t inglebard/dolibarr_ready:9
    - name: docker push
      run: |
        docker push inglebard/dolibarr_ready:9
